version: '3'
services:
    # Nginx
    nginx:
        depends_on:
            - api
            - client
        
        build: ./nginx
        ports:
            - '3050:80'
    # Postgress Database
    postgres_db:
        image: 'postgres'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    # Redis database
    redis_db:
        image: 'redis'
    
    # API service
    api:
        build: ./server
        image: 'manvinigam31/complex_api'
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres_db
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432

    # Worker service
    worker:
        build: ./worker
        image: 'manvinigam31/complex_worker'
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379

    # Frontend
    client:
        build: ./client
        image: 'manvinigam31/complex_client'
        